### ISSUE TITLE
docker file is missing in the repo. Please advise

### ISSUE THREAD

**Issue by zackat3dmedia** [Haroon96/warzone-stats#100]
Working through the details - and at the clone repo stage - and dockerfile cannot be found. Please assist.

**Comment by Haroon96** [comment]
Sorry, faulty commit. I've pushed the required files along with some fixes and it should work now.

**Comment by zackat3dmedia** [comment]
All good.


Do you have any tips for me running this container 24/7 vs just on my PC.
That way if someone tries to get stats in discord and I am logged off - they wouldn't get the stats. Please advise.


Thanks,

Zack Green
Project Manager
3D Media
618 Canal Blvd
Thibodaux, LA 70301
Mobile: 832.292.8577

**Comment by Haroon96** [comment]
The easiest way would be to deploy on a remote server like from linode or AWS but that would be a paid service. 

For free options, look into hosting the container on Heroku with a free MongoDB Atlas instance. See https://medium.com/travis-on-docker/how-to-run-dockerized-apps-on-heroku-and-its-pretty-great-76e07e610e22

The Dockerfile has a MONGO_URI environment variable that you can point to a remote MongoDB Atlas Instance.

**Comment by zackat3dmedia** [comment]
Muhammad,

Thank you for your time. I am working with @Collin ***@***.***> hosting this locally.

Can you direct me to the lines of code where you authenticate to make the API call?
Can you direct me to how you are filtering the data by time (example: user battlenet 5d)


Thanks,

Zack Green
Project Manager
3D Media
618 Canal Blvd
Thibodaux, LA 70301
Mobile: 832.292.8577

**Comment by Haroon96** [comment]
See the function at https://github.com/Haroon96/warzone-stats/blob/777868ce1a0fd67255fabbfd918dd0da9cd97207/src/cod/api.ts#L18

The API is public and doesn't require authentication but sometimes rate-limits.
