### ISSUE TITLE
Getting invalid 

### ISSUE THREAD

**Issue by pballew000** [Haroon96/warzone-stats#39]
Please provide example for the action 

 Invalid syntax, use `!wz register <psn|xbl|atvi> "<username>"` instead.

**Comment by osama-h-rana** [comment]
Hi, can you tell me what command you're using?

**Comment by osama-h-rana** [comment]
`!wz register psn "botmun_"` seems to work for me.

**Comment by pballew000** [comment]
Thank you. Any way we can filter battle royal by game mode? Wanting specifically br solos

**Comment by osama-h-rana** [comment]
Hmm, I don't believe we have that yet. You could create a new issue for that, maybe someone will get to it in time.

Or if you fancy an attempt at it yourself, you could fork the project and make a PR
