### ISSUE TITLE
Mongo Data Models

### ISSUE THREAD

**Issue by mertoksuz** [Haroon96/warzone-stats#44]
hi there, thanks for this awesome work. I just wondering mongo data models. For example, you searching modeIds with given mode. How mongo data models should be ?

Thanks.

**Comment by Haroon96** [comment]
Hi, thank you for your interest! There are 3 mongo collections in the backend: `guilds`, `modes`, and `schedules`.
`guilds` and `schedules` are exactly the same as they're defined in `types.ts`
`modes` is just an array of game modes like below.
```
[{
  "mode": "br",
  "modeIds": [
    "br_br_real",
    "br_brthquad",
    "br_brquads"
  ]
},{
  "mode": "rmbl",
  "modeIds": [
    "brtdm_rmbl"
  ]
},{
  "mode": "plndr",
  "modeIds": [
    "br_dmz_plunquad",
    "br_dmz_plnbld"
  ]
}]
```
The game mode IDs change quite often so we just append the latest modeId to this directly in the database.
