### ISSUE TITLE
All possible modeIds

### ISSUE THREAD

**Issue by darklight147** [Haroon96/warzone-stats#69]
Hi, do you have a list of all possible modeIds, I want to filter by matches which are only battle royal matches

like for example: 
```ts
const matches = matchesResponse.data.matches.filter((x) =>
							x.attributes.modeId.startsWith('br')
);
```

or have a list of all possible battle royal modeIds like:

```ts

const matches = matchesResponse.data.matches.filter((x) => battle_royale_mods.includes(x.attributes.modeId ));
```

Thank you

**Comment by osama-h-rana** [comment]
The modes for `br` that the bot currently looks for are these:
```"br_br_real", 
"br_brthquad", 
"br_brquads", 
"br_jugg_brtriojugr", 
"br_brtrios", 
"br_brduos", 
"br_brsolos", 
"br_brsolo", 
"br_brtriostim_name2", 
"br_truckwar_trwarsquads", 
"br_brhwntrios", 
"br_jugg_jugpmpkn", 
"br_brhwnquad", 
"br_zxp_zmbroy", 
"br_mini_miniroyale", 
"br_brz_brquads", 
"br_brz_brtrios", 
"br_brz_brduos"```

The ones for `rsg` are these:
```
"br_rebirth_rbrthquad", 
"br_rebirth_rbrthtrios", 
"br_rebirth_rbrthduos"
```

The ones for `plndr` are these:
```
"br_dmz_plunquad", 
"br_dmz_plnbld", 
"br_dmz_plndtrios"
```

The ones for `rmbl` is this:
```
"brtdm_rmbl"
```

There's also `br_mini_rebirth_mini_royale_trios` for mini royale but we dont use that.

Any new modes that are added with a playlist update are added to the db. The ones that I've listed above are all of the modes that COD has had so far.

**Comment by darklight147** [comment]
This is perfect, from my side I took a sample of 70 matches from 10 different popular streamers, and this is the list I able to generate:

```json
[
	"br_brsolo",
	"br_brduos",
	"br_rebirth_rbrthquad",
	"br_x2_br_reveal_x2_event/event_title_x2",
	"br_brtrios",
	"br_brquads",
	"br_mini_rebirth_mini_royale_trios",
	"br_dmz_plnbld",
	"br_dmz_plndtrios"
]

```

I should have taken a bigger sample, thank you for the database extraction 😃

**Comment by osama-h-rana** [comment]
Yeah we have another bot that looks at the top 20 players on cod tracker and extracts the modeids from them and posts them to a discord channel: https://github.com/Haroon96/wzs-helper

**Comment by darklight147** [comment]
That's almost what am doing too,

Okay so i increased the sample rate for those players, to 250 matches per player, now I have this list:

```json
[
	"br_brsolo",
	"br_brduos",
	"br_rebirth_rbrthquad",
	"br_rebirth_resurgence_mini",
	"br_dmz_plunquad",
	"br_brdov_dov2",
	"br_reveal_2_dov2",
	"br_mini_rebirth_mini_royale_duos",
	"br_x2_br_reveal_x2_event/event_title_x2",
	"br_brtrios",
	"br_brquads",
	"br_dmz_plndtrios",
	"br_rebirth_rbrthtrios",
	"br_brbbquad",
	"br_mini_rebirth_mini_royale_trios",
	"br_dmz_plnbld",
	"br_reveal_dov",
	"br_brz_brduos",
	"br_rebirth_rbrthduos"
]

```

**Comment by jordan-palmer** [comment]
I am seeing  ['br_88', 'br_25'] in addition to these, any ideas what these game modes are and if they should be counted in the BR modes?

**Comment by osama-h-rana** [comment]
Hmm, we're not actively playing the game right now so I have no clue what those modes could be. Maybe track down the users whose history has those modes and see how many players are in the match, with how many kills? That might give some hints as to what those modes are.

**Comment by jordan-palmer** [comment]
Okay thanks a lot, ill give this a try!
