### ISSUE TITLE
Mismatch between Profile endpoint & Match endpoint of tracker.gg

### ISSUE THREAD

**Issue by darklight147** [Haroon96/warzone-stats#71]
I just want to know how you guys deal with the difference between to two endpoints;

I have been having trouble finding the exact list of modIds described by this value:

![image](https://user-images.githubusercontent.com/39389636/131506224-b90583e8-13be-4be2-8e27-cddcc78cb05f.png)

There are cases where i could determine from the profile endpoint, that a user added 8 kills to there profile, but when i check the match endpoint, i could see they made only 4 for example, or sometimes the profile is only 2 and from matches i can tell its 5, so i wonder does the profile only tracker specific mods, if yes can you provide me the list of mods that is considered by the Battle royale field, in profile endpoint

**Comment by darklight147** [comment]
Please feel free to contact me in discord, to avoid opening issues

**Comment by osama-h-rana** [comment]
Can you elaborate on what exactly is that you're trying to build?
