### ISSUE TITLE
New gamemodes integration (Vanguard Update)

### ISSUE THREAD

**Issue by ghost** [Haroon96/warzone-stats#74]
Hello,

would it be possible to add the new gamemodes to your hosted instance, currently the bot barely fetches any data because of the new gametypes around.

Best regards.

![FGv6OQxXoAQT4Gp](https://user-images.githubusercontent.com/67027904/146538873-60fc281c-2913-4379-9548-fdbc94f208e8.jpg)

**Comment by osama-h-rana** [comment]
Every mode other than plunder duos should already be added.

**Comment by osama-h-rana** [comment]
Just added plunder duos as well, should take effect in a few hours.

**Comment by fl4te** [comment]
That's weird because it doesn't seem to fetch any valid data whenever requested unless the required command parameters have changed. 🤔
