### ISSUE TITLE
Failed to fetch stats! Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by jhoogstraat** [Haroon96/warzone-stats#79]
The error pops up since a few days ago. Did the api change?

**Comment by osama-h-rana** [comment]
Yeah we're aware of the issue, the tracker network protected their api with cloudflare. We'll see if we can figure out a workaround in the next few days. 

If you know of a possible workaround, that'd be quite welcome as well 😁

**Comment by osama-h-rana** [comment]
That's the weird part, I can access the JSON data if I paste the url in a browser but cannot if I use postman to GET the same url, on the same machine. 🤷‍♂️

**Comment by jhoogstraat** [comment]
Then some header must prevent the server from responding, no?

I know that cloudflare does block heroku, though.

**Comment by osama-h-rana** [comment]
Hmm, looks promising. Might take a look in a couple of days.

**Comment by jhoogstraat** [comment]
A workaround is to use curl for now.
I am putting an PR together :)

**Comment by osama-h-rana** [comment]
Hey, that's awesome! We'll happily take PRs :)

**Comment by osama-h-rana** [comment]
@jhoogstraat your curl changes work fine on my system but not on heroku as it gives this error when querying the API:

```
{
  statusCode: 403,
  data: 'error code: 1020',
  headers: [
    {
      result: [Object],
      date: 'Sun, 13 Feb 2022 09:36:14 GMT',
      'content-type': 'text/plain; charset=UTF-8',
      'content-length': '16',
      'x-frame-options': 'SAMEORIGIN',
      'referrer-policy': 'same-origin',
      'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
      expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=FZpOJokXUkpYJqSjMuLGyB8GhA5FcEfgfeIeCrJL41pu7Z%2Fo8jXb9icLNZ18vIzNkFUOu9KZ0DPA4alRrjLT9b%2BKwHPeqLcXA5nPUbC%2Fv%2BBB462Kzrc0OiTxMvj45FGj"}],"group":"cf-nel","max_age":604800}',
      nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
      server: 'cloudflare',
      'cf-ray': '6dcd123cb8b95c2f-IAD'
    }
  ]
}
```

I dont think there's any way around this other than a proxy, is there?

**Comment by jhoogstraat** [comment]
Yeah, thats what I did on Heroku aswell. Really annoying.

**Comment by Haroon96** [comment]
I've moved the bot to a personal server. From what I understand, heroku/aws IPs are flagged by Cloudflare and likely trigger captchas. The bot is up for now but I will monitor this more closely for the next few days.
