### ISSUE TITLE
Register - An error occurred!

### ISSUE THREAD

**Issue by LepClassics** [Haroon96/warzone-stats#85]
hello, when I register I get an error message:

!wz register atvi x2lep4#4885849
@2.LEP.4, An error occurred!

![Yy5sajZpJK](https://user-images.githubusercontent.com/99179613/152774740-8b9a2800-2963-4018-933c-2a58306bf7f0.png)

**Comment by osama-h-rana** [comment]
Hi, yes this is something that we know is broken right now and are working to fix it. Thanks for the bug report though!

**Comment by jhoogstraat** [comment]
#81 should fix this.

**Comment by osama-h-rana** [comment]
@LepClassics this should be resolved now :)
