### ISSUE TITLE
Is it possible to put the bot back online please ?

### ISSUE THREAD

**Issue by sn0wk3ys** [Haroon96/warzone-stats#95]

**Comment by osama-h-rana** [comment]
Sadly, no. The API for Tracker got pretty cumbersome to use, and we don't play the game anymore either so it's hard to know what's going on in the game which makes it very difficult for us to maintain it. 

You're welcome to host the bot on your own though.

**Comment by sn0wk3ys** [comment]
Ok thank you for your quick response and permission to host the bot myself, good luck for the rest !

**Comment by sn0wk3ys** [comment]
Just one more question : how do you start the bot because i don't have the "dist" folder ?

**Comment by osama-h-rana** [comment]
Hmm, I don't quite remember how we setup the bot, I'll do it on a new machine and document the process. Are you on windows/linux/mac?
